on:
  push:
    paths:
      - 'src/main/resources/db/changelog/**'

jobs:
  liquibase-action:
    runs-on: ubuntu-latest
    name: Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: nvoxland/jar-download-action@main
        with:
          groupId: org.postgresql
          artifactId: postgresql
          version: 42.4.0
          outputDirectory: liquibase_libs
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'github/workspace/liquibase_libs'
          changeLogFile: 'db.changelog-master.yaml'
          username: ${{ secrets.DBHOST }}
          password: ${{ secrets.DBPASSOWRD }}
          url: ${{ secrets.DBUSER }}
