on:
  push:
    paths:
      - 'src/main/resources/db/changelog/**'

jobs:
  liquibase-action:
    runs-on: ubuntu-latest
    name: Liquibase Action
    steps:
      - uses: actions/checkout@v3
      - uses: nvoxland/jar-download-action@main
        with:
          groupId: org.postgresql
          artifactId: postgresql
          version: 42.4.0
          outputDirectory: liquibase_libs
      - uses: liquibase-github-actions/update@v4.21.1
        with:
          changeLogFile: 'db.changelog-master.yaml'
          username: ${{ secrets.DBUSER }}
          password: ${{ secrets.DBPASSOWRD }}
          url: ${{ secrets.DBHOST }}
